name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Debug: Check Directory Structure
        run: ls -R

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ${{ github.workspace }}

      - name: Log in to GitHub Container Registry (GHCR)
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          GHCR_USERNAME: ${{ github.actor }}
        run: echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin

      - name: Set Lowercase Image Name
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/my-app:latest"
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase (GHCR requirement)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          echo "Building Docker image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
      
      - name: Push Docker Image to GHCR
        run: |
          echo "Pushing Docker image: $IMAGE_NAME"
          docker push $IMAGE_NAME
