name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to GitHub Container Registry (GHCR)
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: echo "$GHCR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-app:latest
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Docker Image to GHCR
        run: docker push $IMAGE_NAME
